agenda_eletronica/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :phones
  resources :adresses
  resources :contacts
  resources :kinds #cria 8 rotas automaticamente
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

agenda_eletronica/app/models/adress.rb
class Adress < ApplicationRecord
  belongs_to :contact
end

agenda_eletronica/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

agenda_eletronica/app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :kind
  has_one :adress, dependent: :destroy
  has_many :phones, dependent: :destroy

  accepts_nested_attributes_for :adress
  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true
  validates :email, presence: true
end

agenda_eletronica/app/models/kind.rb
class Kind < ApplicationRecord
	has_many :contacts, dependent: :destroy

  validates :description, presence: true
end

agenda_eletronica/app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact
end

agenda_eletronica/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

agenda_eletronica/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_options_for_select, only: [:new, :edit, :update, :create]
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all.order(:name).page(params[:page]).per(15)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_adress
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: I18n.t('messages.created')}
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_path, notice: I18n.t('messages.destroyed')}
      format.json { head :no_content }
    end
  end

  private

    def set_options_for_select
      @kind_options_for_select = Kind.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :kind_id, :rmk,
        adress_attributes: [:street, :city, :state],
        phones_attributes: [:id, :phone, :_destroy])
    end
end

agenda_eletronica/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

agenda_eletronica/app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]

  # GET /kinds
  # GET /kinds.json
  def index #nome do arquivo
    @kinds = Kind.all
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to kinds_path, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to kinds_path, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_path, notice: I18n.t('messages.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

agenda_eletronica/app/helpers/adresses_helper.rb
module AdressesHelper
end

agenda_eletronica/app/helpers/application_helper.rb
module ApplicationHelper
	ESTADOS_BRASILEIROS = [
        ["Acre", "AC"],
        ["Alagoas", "AL"],
        ["Amapá", "AP"],
        ["Amazonas", "AM"],
        ["Bahia", "BA"],
        ["Ceará", "CE"],
        ["Distrito Federal", "DF"],
        ["Espírito Santo", "ES"],
        ["Goiás", "GO"],
        ["Maranhão", "MA"],
        ["Mato Grosso", "MT"],
        ["Mato Grosso do Sul", "MS"],
        ["Minas Gerais", "MG"],
        ["Pará", "PA"],
        ["Paraíba", "PB"],
        ["Paraná", "PR"],
        ["Pernambuco", "PE"],
        ["Piauí", "PI"],
        ["Rio de Janeiro", "RJ"],
        ["Rio Grande do Norte", "RN"],
        ["Rio Grande do Sul", "RS"],
        ["Rondônia", "RO"],
        ["Roraima", "RR"],
        ["Santa Catarina", "SC"],
        ["São Paulo", "SP"],
        ["Sergipe", "SE"],
        ["Tocantins", "TO"]
  ]

  def options_for_states(selected)
  	options_for_select(ESTADOS_BRASILEIROS, selected)
  end

end

agenda_eletronica/app/helpers/contacts_helper.rb
module ContactsHelper
end

agenda_eletronica/app/helpers/home_helper.rb
module HomeHelper
end

agenda_eletronica/app/helpers/kinds_helper.rb
module KindsHelper
end

agenda_eletronica/app/helpers/phones_helper.rb
module PhonesHelper
end

agenda_eletronica/app/views/contacts/_form.html.erb
<br>
<%= form_for(@contact, html: { class: "basic-grey"}) do |form| %>
  <h1>Contatos</h1>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :kind_id %>
    <%= form.collection_select(:kind_id, @kind_options_for_select, :id, :description) %>
  </div>

  <%= form.fields_for :adress do |adress_fields| %>
    <div class="field"><br>
      <%= adress_fields.label :street %><br>
      <%= adress_fields.text_field :street %>
    </div>
    <div class="field">
      <%= adress_fields.label :city %><br>
      <%= adress_fields.text_field :city %>
    </div>
    <div class="field">
      <%= adress_fields.label :state %><br>
      <%= adress_fields.select :state, options_for_states(@contact.adress.state) %>
    </div>
  <% end %>

  <div id="phones">
    <%= form.fields_for :phones do |phones_fields| %>
      <%= render "phone_fields", f: phones_fields %>
    <% end %>

    <div class="field">
      <br><%= link_to_add_association('Adicionar Telefone', form, :phones, class: "badge badge-pill badge-secondary") %>
    </div>
  </div>

  <div class="field">
    <br><%= form.label :rmk %>
    <%= form.text_area :rmk %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar", class: "btn btn-danger" %>
    <%= link_to t('buttons.back'), contacts_path, class: "btn btn-secondary" %>
  </div>

  <% if @contact.errors.any? %>
    <% contact.errors.full_messages.each do |message| %>
      <script>
        $.notify("<%= message %>", "error");
      </script>
    <% end %>
  <% end %>
<% end %>

agenda_eletronica/app/views/contacts/_phone_fields.html.erb
    <div class="nested-fields">
        <div class="field">
          <%= f.label :phone %><br>
          <%= f.text_field :phone, class: "phone-field" %>
          <%= link_to_remove_association('remover', f, class: "badge badge-pill badge-dark") %>
        </div>
    </div>

agenda_eletronica/app/views/contacts/edit.html.erb
<br>

<%= render 'form', contact: @contact %>

agenda_eletronica/app/views/contacts/index.html.erb
<br>
<div class="basic-grey">
  <script>
    $.notify("<%= notice %>", "success");
  </script>
  <h1><%= @contacts.model_name.human(count: @contacts.count) %></h1>

  <table>
    <thead>
      <tr>
        <th><%= @contacts.human_attribute_name("name") %></th>
        <th><%= @contacts.human_attribute_name("kind") %></th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr style="background: <%= cycle('#f0f0f5', 'white') %>">
          <td><%= contact.name %></td>
          <td><%= contact.kind.description %></td>
          <td><%= link_to t('buttons.edit'), edit_contact_path(contact), class: "badge badge-pill badge-secondary" %></td>
          <td><%= link_to t('buttons.destroy'), contact, method: :delete, data: { confirm: t('messages.confirm') }, class: "badge badge-pill badge-dark" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br><%= page_entries_info @contacts %><br>
  <p style="text-align: right;">
    <%= link_to_prev_page @contacts, t('buttons.prev'), class: "badge badge-pill badge-secondary"  %>
    <%= link_to_next_page @contacts, t('buttons.next'), class: "badge badge-pill badge-dark" %>
  </p>
  <br><br>
  <%= link_to t('buttons.home'), home_index_path, class: "btn btn-secondary" %>
  <%= link_to t('buttons.new'), new_contact_path, class: "btn btn-danger" %>
</div>

agenda_eletronica/app/views/contacts/new.html.erb
<%= render 'form', contact: @contact %>

agenda_eletronica/app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @contact.kind %>
</p>

<p>
  <strong>Rmk:</strong>
  <%= @contact.rmk %>
</p>

<%= link_to t('buttons.edit'), edit_contact_path(@contact) %> |
<%= link_to t('buttons.back'), contacts_path %>

agenda_eletronica/app/views/home/index.html.erb
<br>
<div class="basic-grey">
<h1>Seja Bem-vindo!</h1>

<ul>
	<li><src href="sprite.svg#si-glyph-bullet-list-2" /></svg-icon><%= link_to "Tipos", kinds_path, class: "btn btn-light btn-lg" %></li>
	<li><src href="sprite.svg#si-glyph-old-phone" /></svg-icon><%= link_to "Contatos", contacts_path, class: "btn btn-light btn-lg" %></li>
</ul>
</div>

agenda_eletronica/app/views/kinds/_form.html.erb
<br>
<%= form_with(model: kind, local: true, html: { class: "basic-grey"}) do |form| %>
  <h1>Tipos de Contatos</h1>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit "Enviar", class: "btn btn-danger" %>
    <%= link_to t('buttons.back'), kinds_path, class: "btn btn-secondary" %>
  </div>

  <% if kind.errors.any? %>
    <% kind.errors.full_messages.each do |message| %>
      <script>
        $.notify("<%= message %>", "error");
      </script>
    <% end %>
  <% end %>
<% end %>

agenda_eletronica/app/views/kinds/edit.html.erb
<%= render 'form', kind: @kind %>

agenda_eletronica/app/views/kinds/index.html.erb
<br>
<div class="basic-grey">
  <script>
    $.notify("<%= notice %>", "success");
  </script>

  <h1><%= @kinds.model_name.human(count: @kinds.count) %></h1>

  <table>
    <thead>
      <tr>
        <th><%= @kinds.human_attribute_name("description") %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @kinds.each do |kind| %>
        <tr>
          <td><%= kind.description %></td>
          <td><%= link_to t('buttons.edit'), edit_kind_path(kind), class: "badge badge-pill badge-secondary" %></td>
          <td><%= link_to t('buttons.destroy'), kind, method: :delete, data: { confirm: t('messages.confirm') }, class: "badge badge-pill badge-dark" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to t('buttons.home'), home_index_path, class: "btn btn-secondary" %>
  <%= link_to t('buttons.new'), new_kind_path, class: "btn btn-danger" %>

</div>

agenda_eletronica/app/views/kinds/new.html.erb
<%= render 'form', kind: @kind %>

agenda_eletronica/app/views/kinds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @kind.description %>
</p>

<%= link_to t('buttons.edit'), edit_kind_path(@kind) %> |
<%= link_to t('buttons.back'), kinds_path %>

agenda_eletronica/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agenda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>